<?php
// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

add_action('rest_api_init', function () {
    register_rest_route('wc/v3', '/order-document/send', [
        'methods' => 'POST',
        'callback' => 'wha_send_order_document_with_pdf',
        'permission_callback' => function () {
            return current_user_can('manage_woocommerce');
        }
    ]);
});

/**
 * Maps the document type to the registered WC_Email class.
 */
function wha_order_document_email_class_map()
{
    return [
        'invoice'          => 'WC_Email_Invoice',
        'invoice_reminder' => 'WC_Email_Invoice_Reminder',
        'offer'            => 'WC_Email_Offer',
        'offer_reminder'   => 'WC_Email_Offer_Reminder',
    ];
}

/**
 * Sends a document mail with an ALREADY generated PDF (base64) as attachment.
 *
 * Unlike /notifications and /reminders (which regenerate the PDF from the posted
 * document positions), this attaches the PDF exactly as provided — used for
 * WooCommerce order invoices, where the real PDF is generated by WooCommerce.
 *
 * @param WP_REST_Request $request
 * @return WP_REST_Response|WP_Error
 */
function wha_send_order_document_with_pdf(WP_REST_Request $request)
{
    $params = $request->get_json_params();
    $to     = $params['to'] ?? '';
    $number = $params['number'] ?? '';
    $base64 = $params['base64'] ?? '';
    $type   = $params['type'] ?? 'invoice';

    if (empty($to)) {
        return new WP_Error('missing_to', 'The recipient email address is missing or empty.', ['status' => 400]);
    }

    $class_map = wha_order_document_email_class_map();
    if (! isset($class_map[$type])) {
        return new WP_Error('invalid_type', 'Unknown document type.', ['status' => 400]);
    }

    if (empty($base64)) {
        return new WP_Error('missing_pdf', 'The PDF attachment is missing or empty.', ['status' => 400]);
    }

    $pdf = base64_decode($base64, true);
    if ($pdf === false) {
        return new WP_Error('invalid_pdf', 'Could not decode the PDF attachment.', ['status' => 400]);
    }

    $prefix    = strpos($type, 'invoice') === 0 ? 'Rechnung_' : 'Angebot_';
    $file_name = sanitize_file_name($prefix . ($number !== '' ? $number : 'dokument') . '.pdf');
    $pdf_path  = sys_get_temp_dir() . DIRECTORY_SEPARATOR . $file_name;
    file_put_contents($pdf_path, $pdf);

    // Ensure the custom WC_Email classes are registered/loaded.
    WC()->mailer();

    $class = $class_map[$type];
    if (! class_exists($class)) {
        return new WP_Error('missing_class', 'Email class not available: ' . $class, ['status' => 500]);
    }

    $email = new $class();
    $email->number    = $number;
    $email->recipient = $to;

    $sent = $email->send_email($to, [$pdf_path]);

    if ($sent) {
        return rest_ensure_response(['success' => true, 'message' => 'Email sent successfully!']);
    }

    return new WP_Error('send_failed', 'Failed to send email.', ['status' => 500]);
}
